profiles: Update to header 256
KhronosGroup/Vulkan-Profiles pull request #463
Opened 2023-07-07 14:41 UTC by ziga-lunarg

2023-07-07 15:56 UTC, juan-lunarg approved these changes

2023-07-07 19:45 UTC, juan-lunarg requested changes
${VULKAN_HEADERS_REGISTRY_DIRECTORY} was removed.

Use "${VULKAN_HEADERS_INSTALL_DIR}/${CMAKE_INSTALL_DATADIR}/vulkan/registry" instead.

2023-07-10 09:42 UTC, christophe-lunarg approved these changes

2023-07-10 16:44 UTC, juan-lunarg approved these changes

2023-07-10 16:56 UTC, merged